name: Maven CI for non-release branches

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven local repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Build and test with Maven
        run: mvn -B clean package --file pom.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/target/**/TEST-*.xml"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: JaCoCo coverage
        uses: madrapps/jacoco-report@v1.2
        if: always() # always run even if the previous step fails
        with:
          paths: "${{ github.workspace }}/pig4j-core/target/site/jacoco/jacoco.xml,${{ github.workspace }}/pig4j-base-layers/target/site/jacoco/jacoco.xml"
          token: ${{ secrets.ACTIONS_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: JaCoCo coverage report

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
