name: Maven CI for non-release branches

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and test with Maven
        run: mvn -B clean package --file pom.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "target/**/TEST-*.xml"
      - name: JaCoCo coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        if: always() # always run even if the previous step fails
        with:
          paths: "**/jacoco.xml"
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
